### PR TITLE
Update Corsican translation on August 2023

### PR DESCRIPTION
**Pull request by Patriccollu**
Hello,

This is an update of **Corsican** localization to take into account the following commits:

  * https://github.com/enzo1982/freac/commit/6fe12a1a0541a949d4a2f0e928388966b7991e7b Use "disc" with a "c" to refer to CDs.
  * https://github.com/enzo1982/freac/commit/4689df2d6794e082a39c60f4728e751e3cb7797b Change "cover art" to "album art" in UI and code base.

I also changed a couple of existing translations and added a comment - regarding Corsican translation history - at the beginning of file.

Cheers,
Patriccollu.

### CODE REVIEW

**Comment by Patriccollu** [comment]
Hello,

I've fixed an error on the author's URL which impacted `freac_co.xml`, `setup_co.xml`, `tips_co.xml`,  and `eupdate_co.xml`.

My first idea was to use the local branch `freac_co_20230801` previously created for `freac_co.xml` but each update on the three other members created a new and different local branch! Then I eventually updated my first local branch with 3 local Pull Requests.

As I'm not an expert on GitHub -  ;-) - I don't know if it was the simplest way to do! Please double check.

Best regards,
Patriccollu.

**Comment by Patriccollu** [comment]
@enzo1982 
Hi Robert,

Please can you tell me if you need something else from me on this PR?

Cheers,
Patricollu.

**Comment by enzo1982** [comment]
Hi Patriccollu,

Sorry for the delay! I didn't have much time to work on fre:ac in the past months, but I hope this will change soon.

Thank you so much for the update!

Best,
Robert

**Comment by Patriccollu** [comment]
@enzo1982 
Hi Robert,

Thank you for the merge. And don't worry for the delay. I understand that sometimes the volunteers have something else to do other than coding, merging or translating! ;-)

Cheers,
Patriccollu.

**Pull request merged**
