### PR TITLE
Add vector icon to Haiku resources

### PR DESCRIPTION
**Pull request by humdingerb**
Originally by lelldorin, I optimized it and added a shadow.

### CODE REVIEW

**Comment by humdingerb** [comment]
Latest release for Haiku is v1.1.1. What are the chances for an update to 1.1.3? :)

**Comment by enzo1982** [comment]
Thank you for your PR!

Honestly, I think this icon is a bit too far from the original fre:ac icon to really be recognizable. I think I'd prefer something like a vectorized version of the PNG icon instead. I did some experiments in that direction today and first results look promising. I just sent lelldorin a mail including my first attempt at a vectorized icon ([HVIF here](https://github.com/enzo1982/freac/files/5863469/freac.hvif.zip)). That will not be the final version, though. I hope I can further reduce the number of paths to make it smaller and also optimize it to make it look a bit better.

Regarding fre:ac 1.1.3, yes, I'll start working on it. I had some update issues with my Haiku installation back in summer (updating OpenSSL caused all TLS connections to fail, including pkgman) and wanted to investigate that later. Well, later never happened, so I didn't get around to updating the recipes. But today I updated directly to beta 2 and everything is working great right now. :)

There will probably be some dependencies that need to be updated, so I'll do those first. Then my own libraries and fre:ac. Should not take more than 2-3 days.

**Comment by humdingerb** [comment]
> I think I'd prefer something like a vectorized version of the PNG icon instead.

Yeah, but that normally doesn't work that great. If you had the vector workfiles of the icon it'd be easy. It does look like the original icon was created in a vector app, not as bitmap graphics.

> There will probably be some dependencies that need to be updated, so I'll do those first. Then my own libraries and fre:ac. > Should not take more than 2-3 days.

Very nice!

**Comment by enzo1982** [comment]
fre:ac is updated to 1.1.3 on HaikuPorts now, but still without a vector icon. I'll finish the new icon this week and will include it with 1.1.4 which I plan to release next weekend.

> If you had the vector workfiles of the icon it'd be easy. It does look like the original icon was created in a vector app, not as bitmap graphics.

The icon is based on some icons from the Crystal Clear icon set. Only some of those have ever been released as vector images, so I only have a vector version of the gears, but not the disc or note. I have separate disc and note icons, though, so I can vectorize them separately, which should give better results.

**Comment by humdingerb** [comment]
> fre:ac is updated to 1.1.3

So I have seen, thanks!

> I only have a vector version of the gears, but not the disc or note.

That's good, the gears are the more difficult shapes... :)

**Comment by enzo1982** [comment]
So, I finished the vector icon:

- https://github.com/enzo1982/freac/blob/master/icons/freac.svg
- https://github.com/enzo1982/freac/blob/master/icons/freac.hvif

I'll be using that in the upcoming 1.1.4 update. Just a few more days...

**Comment by humdingerb** [comment]
Good. Size-wise not really in the HVIF spirit, but normal when going from SVG to HVIF than vice-versa... :)
Anyway, time to close this PR. Looking forward to 1.1.4!

**Pull request closed without merging**
