### PR TITLE
AppImage

### PR DESCRIPTION
**Pull request by probonopd**
This PR, when merged, will compile Fre:ac on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload an [AppImage](http://appimage.org/) to your GitHub Releases page.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter
- No repositories needed. Suitable/optimized for air-gapped (offline) machines

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

__PLEASE NOTE:__ For this to work, you need to enable Travis CI for your repository as [described here](https://travis-ci.org/getting_started) __prior to merging this__, if you haven't already done so. Also, You need to set up `GITHUB_TOKEN` in Travis CI for this to work; please see https://github.com/probonopd/uploadtool.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

### CODE REVIEW

**Comment by probonopd** [comment]
The Mac build failure is, I think, unrelated to my changes?

Here is an AppImage for testing:
https://github.com/probonopd/freac/releases

**Comment by enzo1982** [comment]
Thanks alot for your work! I will have a closer look in the next few days.

I already have some remarks, though:

- The `usr/lib/boca` folder containing the BoCA components is missing. Without the components fre:ac cannot really do anything.
- Is there a way to run the `freaccmd` command instead of `freac` when running the AppImage?
- The` smooth-translator` application should be included so users can edit translations.
- There are no codecs, processing libraries or auxillary programs included, so the bundle can use only libraries/programs already installed on the host system. For easier setup, libraries and auxillary programs should be included in the AppImage. This should include: libcdio and libcdio-paranoia, libmp3lame, libmpg123, libfaac or libfdk-aac, libfaad2, libFLAC, libMAC, libmp4v2, libogg, libopus, librnnoise, librubberband, libsamplerate, libsndfile, libspeex, libvorbis, avconv or ffmpeg, mpcdec, mpcenc, wavpack and wvunpack
- Ideally these libraries/programs should be the latest versions and use the patches listed at https://freac.org/downloads-mainmenu-33/214-codec-sources-and-patches
- A stand-alone packaging script for building outside of Travis CI would be great. This could be put in `packaging/appimage`. There already is something like that to help me package the official releases in the `tools` folder.

The macOS build failure is unrelated to your changes indeed. It's a Homebrew update error that needs to be fixed by the Travis CI team.

**Comment by probonopd** [comment]
> There are no codecs, processing libraries or auxillary programs included

How does Fre:ac load those libraries?

**Comment by probonopd** [comment]
> Is there a way to run the `freaccmd` command instead of `freac` when running the AppImage?

It could be done by writing a custom `AppRun` script, similar to this one.

```
#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
# Allow the AppImage to be symlinked to e.g., /usr/bin/freaccmd
# or called with ./Fre.ac*.AppImage freaccmd ...
if [ ! -z $APPIMAGE ] ; then
  BINARY_NAME=$(basename "$ARGV0")
else
  BINARY_NAME=$(basename "$0")
fi
if [ ! -z "$1" ] && [ -e "$HERE/bin/$1" ] ; then
  MAIN="$HERE/bin/$1" ; shift
elif [ ! -z "$1" ] && [ -e "$HERE/usr/bin/$1" ] ; then
  MAIN="$HERE/usr/bin/$1" ; shift
elif [ -e "$HERE/bin/$BINARY_NAME" ] ; then
  MAIN="$HERE/bin/$BINARY_NAME"
elif [ -e "$HERE/usr/bin/$BINARY_NAME" ] ; then
  MAIN="$HERE/usr/bin/$BINARY_NAME"
else
  MAIN="$HERE/bin/freac"
fi
```

**Comment by enzo1982** [comment]
> How does Fre:ac load those libraries?

The components in `lib/boca` are loaded dynamically by `libboca-1.0.so.0`. Components in turn usually load their dependencies dynamically as well (except for the CDIO components which are linked against `libcdio*.so`). The dynamic loading probably means that those dependencies cannot be auto-detected and have to be explicitly mentioned.

That said, the new AppImage already works much better. Components are loaded and access the codecs installed on the host (still, having bundled codecs would be preferable). Auxillary programs present on the host are detected too.

CD ripping does not work yet, though. The `libcdio*` libraries are bundled, but seem not to be found by the dynamic linker similarly to what we had with `freac.so`. So I guess `lib/boca/boca_decoder_cdio.1.0.so` and `lib/boca/boca_deviceinfo_cdio.1.0.so` need the rpath set too.

Or alternatively just set `LD_LIBRARY_PATH` to `$HERE/usr/lib` in AppRun. That might make the whole rpath thing unnecessary.

**Comment by probonopd** [comment]
Everything that gets loaded with `dlopen()` cannot be detected by `linuxdeployqt` automatically and needs to be specified manually. Thanks for your feedback, I will see how I can improve...

**Comment by probonopd** [comment]
How do I best test for full functionality @enzo1982?

**Comment by probonopd** [comment]
Do you happen to have the Ubuntu 14.04 package names handy for

>  libmp3lame, libmpg123, libfaac or libfdk-aac, libfaad2, libFLAC, libMAC, libmp4v2, libogg, libopus, librnnoise, librubberband, libsamplerate, libsndfile, libspeex, libvorbis, avconv or ffmpeg, mpcdec, mpcenc, wavpack and wvunpack

**Comment by probonopd** [comment]
This looks better, doesn't it?

better

Still something major missing?

**Comment by probonopd** [comment]
It seems like all libraries in `usr/lib/boca/` have all of their dependencies met, at least the ones they link against "normally" and not using `dlopen()`:

```
me@host:~$ Downloads/fre.ac-ef7be2a-x86_64.AppImage --appimage-extract
me@host:~$ find squashfs-root/usr/lib/boca/ -name '*.so' -exec ldd {} \; | grep not
# (nothing) 
```

**Comment by enzo1982** [comment]
> How do I best test for full functionality @enzo1982?

Full functionality is not really defined for fre:ac. The libraries I listed should provide a standard functionality set, but there are no automated tests for it. So the best I can think of is me looking over your updates and telling you what's missing.

> Do you happen to have the Ubuntu 14.04 package names handy for [...]

The listed libraries are all dynamically loaded. The relevant package names are:

`libmp3lame0, libmpg123-0, libfaac0, libfdk-aac0, libfaad2, libflac8, libmp4v2-2, libogg0, libopus0, librubberband2, libsamplerate0, libsndfile1, libspeex1, libvorbis0a, libvorbisenc2, libav-tools, musepack-tools, wavpack`

libMAC (Monkey's Audio) and RNNoise are not available as packages on Ubuntu 14.04.

> This looks better, doesn't it? Still something major missing?

Much better, yes! 

The VisualOn AAC encoder is used as a last resort if nothing better is found, so it seems FAAC or better FDK-AAC are still missing. Also I don't see a CD icon in the toolbar, but it might be that you don't have a CD drive.

I didn't try the latest build myself, will do that tomorrow.

Many thanks for your work on this thus far! This certainly saves me some days of work vs. digging into building AppImages myself and figuring everything out.

**Comment by probonopd** [comment]
Reminder to self: Need to fix
https://travis-ci.com/probonopd/freac/jobs/170011630#L3549-L3582
by not using wildcards

**Comment by enzo1982** [comment]
Just had another look at the updated AppImage. Looks much better now; even CD ripping works on my system! :)

A few remarks:

- Some libraries are present twice - once in usr/lib and once in usr/lib/x86_64-linux-gnu, e.g. libvorbis
- The libraries in x86_64-linux-gnu do not seem to be found/loaded, e.g. I cannot see any AAC encoder on my system even though libfaac and libfdk-aac are present in x86_64-linux-gnu
- I guess hard-coding x86_64-linux-gnu in .travis.yml would make it difficult to build for other architectures

Also, some libraries are outdated (like libcdio 0.83 from 2011 when the current version is libcdio 2.0), but I can deal with bundling custom-built libraries later.

**Comment by probonopd** [comment]
Do you think you could take over from here?

**Comment by probonopd** [comment]
Sorry for not having noticed the macOS breakage; should be easily fixable by adding a few more if clauses like the ones that are already there.

**Comment by probonopd** [comment]
@enzo1982 do you still need something from my side? Thanks. :+1:

**Comment by enzo1982** [comment]
@probonopd: Not really right now, thank you!

Now that Snap support is squared away, AppImage is my top priority. I just want to make a few improvements before a release to bring the AppImage up to par with the other package formats:

- Include latest codec versions with SIMD and other optimization patches (which means building the codecs as part of the packaging process)
- Include a custom built ffmpeg with ALAC and WMA support (the .deb packaged version does not support these)
- Include support for Monkey's Audio and RNNoise
- Include support for using the iTunes AAC encoder (i.e. building the [BoCA Core Audio Connect](https://github.com/enzo1982/BoCA/tree/master/components/encoder/coreaudioconnect) Wine bridge)
- Support other architectures (at least i686, armhf and aarch64)

Sounds like a lot, but it's basically just putting existing build scripts together. With these improvements, the AppImages can then completely replace the current .tar.gz packages starting with the next release and be the default package format for fre:ac on Linux.

I will probably use appimagetool directly instead of linuxbundleqt though, in order to get other architectures working. I already have a script that converts the release .tar.gz to an AppImage using appimagetool - just need to do some more testing before releasing.

On weekdays I only have about one hour to work on the project, so this might take until the weekend. Should not take any longer than that as of now though. :)

**Comment by enzo1982** [comment]
I addressed all the issues listed above, except for the multi architecture support. Will do that separately.

Thanks again!

**Comment by probonopd** [comment]
Looks like my script trickery breaks running the app in [Firejail](https://github.com/netblue30/firejail), to be investigated.

```
/run/firejail/appimage/.appimage-8649/AppRun: line 22: /run/firejail/appimage/.appimage-8649/: Is a directory
/run/firejail/appimage/.appimage-8649/AppRun: line 22: exec: /run/firejail/appimage/.appimage-8649/: cannot execute: Is a directory
```

**Comment by enzo1982** [comment]
The problem is testing for existence of `$HERE/$BINARY_NAME` with `-e` in AppRun.

When running in firejail, `$ARGV0` appears to be empty. Thus `$BINARY_NAME` will be empty. In that case, `-e` still returns true, because `$HERE/$BINARY_NAME` is now equivalent to `$HERE` which is an existing directory.

A possible solution is to test for `-x && ! -d` like so: `if [ -x "$HERE/$BINARY_NAME" ] && [ ! -d "$HERE/$BINARY_NAME" ] ; then`

I'll push the fix this evening.

**Pull request merged**
